### ISSUE TITLE
Causal discovery and inference - concepts and recent methodological advances 

### ISSUE THREAD

**Issue by ymlgithub** [ymlgithub/yml.red#3]
https://yml.red/2019/10/12/Causal_discovery_and_inference-concepts_and_recent_methodological_advances/ 

 摘要
 这篇论文介绍了因果推断中的核心概念和原则、从独立同分布数据和时序数据中进行因果发现的方法。论文主要分为以下5个部分：
 
 干预、因果模型、样本预测模型、因果预测模型和结构化因果模型等概念。
 
 基于约束的因果发现方法，该方法依赖于数据中的条件独立关系。
 
 基于结构化方程模型的因果发现方法，其关键问题在于如何确定变量间因果关系的方向。误差项和因变量之间的独立性以及结构化方程上适当的结

**Comment by Yangzyangjin** [comment]
牛掰
